#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: notebook.ipynb

import time
from isolation import Board


# Credits if any
# 1)
# 2)
# 3)

class OpenMoveEvalFn:
    def score(self, game, my_player=None):
        """Score the current game state
        Evaluation function that outputs a score equal to how many
        moves are open for AI player on the board minus how many moves
        are open for Opponent's player on the board.

        Note:
            If you think of better evaluation function, do it in CustomEvalFn below.

            Args
                game (Board): The board and game state.
                my_player (Player object): This specifies which player you are.

            Returns:
                float: The current state's score. MyMoves-OppMoves.

            """

        # TODO: finish this function!
        player_moves = game.get_player_moves(my_player)
        opposite_moves = game.get_opponent_moves(my_player)
        return len(player_moves) - len(opposite_moves)
        raise NotImplementedError


class CustomEvalFn:

    def score(self, game, my_player=None):
        """Score the current game state.

        Custom evaluation function that acts however you think it should. This
        is not required but highly encouraged if you want to build the best
        AI possible.

        Args:
            game (Board): The board and game state.
            my_player (Player object): This specifies which player you are.

        Returns:
            float: The current state's score, based on your own heuristic.
        """

        # TODO: finish this function!
        player_moves = game.get_player_moves(my_player)
        opposite_moves = game.get_opponent_moves(my_player)
        m = (len(game.get_active_moves()) / (game.height * game.width))
        if m <= 0.5:
            return (2 * len(player_moves)) - len(opposite_moves)
        else:
            return len(player_moves) - (2 * len(opposite_moves))
        raise NotImplementedError


######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################


class CustomPlayer:
    # TODO: finish this class!
    """Player that chooses a move using your evaluation function
    and a minimax algorithm with alpha-beta pruning.
    You must finish and test this player to make sure it properly
    uses minimax and alpha-beta to return a good move."""

    def __init__(self, search_depth=6, eval_fn=CustomEvalFn()):
        """Initializes your player.

        if you find yourself with a superior eval function, update the default
        value of `eval_fn` to `CustomEvalFn()`

        Args:
            search_depth (int): The depth to which your agent will search
            eval_fn (function): Evaluation function used by your agent
        """
        self.eval_fn = eval_fn
        self.search_depth = search_depth

    def move(self, game, time_left):
        """Called to determine one move by your agent

        Note:
            1. Do NOT change the name of this 'move' function. We are going to call
            this function directly.
            2. Call alphabeta instead of minimax once implemented.
        Args:
            game (Board): The board and game state.
            time_left (function): Used to determine time left before timeout

        Returns:
            tuple: (int,int): Your best move
        """
        best_move, utility = alphabeta(self, game, time_left, self.search_depth)

        return best_move

    def utility(self, game, my_turn):
        """You can handle special cases here (e.g. endgame)"""
        return self.eval_fn.score(game, self)


###################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE CLASS! ################
###### IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ###########
###################################################################


def minimax(player, game, time_left, depth, my_turn=True):
    """Implementation of the minimax algorithm.
    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you
            need from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer()).
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """
    return mm_max_function(player, game, time_left, depth)
    raise NotImplementedError


def mm_max_function(player, game, time_left, depth):
    if time_left() < 20 or depth == 0:
        return None, player.utility(game, True)
    max_eval = float('-inf')
    best_move = None
    for p_move in game.get_player_moves(game.get_active_player()):
        new_board, game_over, _ = game.forecast_move(p_move)
        if game_over is True:
            return p_move, float('inf')
        last_move, next_eval = mm_min_function(player, new_board, time_left, depth - 1)
        if next_eval > max_eval:
            max_eval = next_eval
            best_move = p_move
    return best_move, max_eval


def mm_min_function(player, game, time_left, depth):
    if time_left() < 20 or depth == 0:
        return None, player.utility(game, False)
    min_eval = float('inf')
    best_move = None
    for o_move in game.get_player_moves(game.get_active_player()):
        new_board, game_over, _ = game.forecast_move(o_move)
        if game_over is True:
            return o_move, float('-inf')
        last_move, next_eval = mm_max_function(player, new_board, time_left, depth - 1)
        if next_eval < min_eval:
            min_eval = next_eval
            best_move = o_move
    return best_move, min_eval


######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def alphabeta(player, game, time_left, depth, alpha=float("-inf"), beta=float("inf"), my_turn=True):
    """Implementation of the alphabeta algorithm.

    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you need
            from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer())
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        alpha (float): Alpha value for pruning
        beta (float): Beta value for pruning
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """

    # TODO: finish this function!
    return ab_max_function(player, game, time_left, depth, alpha, beta)
    raise NotImplementedError


def ab_max_function(player, game, time_left, depth, alpha, beta):
    if time_left() < 20 or depth == 0:
        return None, player.utility(game, True)
    max_eval = float('-inf')
    best_move = None
    p_moves = order_moves(player, game, True)
    for p_move in p_moves:
        new_board, game_over, _ = game.forecast_move(p_move)
        if game_over is True:
            return p_move, float('inf')
        last_move, next_eval = ab_min_function(player, new_board, time_left, depth - 1, alpha, beta)
        if next_eval > max_eval:
            max_eval = next_eval
            best_move = p_move
            alpha = max(alpha, next_eval)
        if max_eval >= beta:
            break
    return best_move, max_eval


def ab_min_function(player, game, time_left, depth, alpha, beta):
    if time_left() < 20 or depth == 0:
        return None, player.utility(game, False)
    min_eval = float('inf')
    best_move = None
    # o_moves = order_moves(player, game, False)
    for o_move in game.get_player_moves(game.get_active_player()):
        new_board, game_over, _ = game.forecast_move(o_move)
        if game_over is True:
            return o_move, float('-inf')
        last_move, next_eval = ab_max_function(player, new_board, time_left, depth - 1, alpha, beta)
        if next_eval < min_eval:
            min_eval = next_eval
            best_move = o_move
            beta = min(beta, min_eval)
        if min_eval <= alpha:
            break
    return best_move, min_eval


def order_moves(player, game, my_turn=True):
    move_utility_dict = dict()
    for move in game.get_player_moves(game.get_active_player()):
        new_board, game_over, _ = game.forecast_move(move)
        if game_over is True:
            killer_utility = float('inf') if my_turn is True else float('-inf')
            move_utility_dict[move] = killer_utility
        else:
            move_utility_dict[move] = player.utility(new_board, my_turn)
    return {k: v for k, v in sorted(move_utility_dict.items(), key=lambda item: item[1], reverse=my_turn)}


def id_alpha_beta(player, game, time_left, max_depth):
    best_move = None
    best_utility = float('-inf')
    for d in range(max_depth):
        move, utility = alphabeta(player, game, time_left, (d + 1))
        if utility == float('inf'):
            best_move = move
            break
        if utility == float('-inf'):
            break
        if move is not None and utility > best_utility:
            best_move = move
            best_utility = utility
    return best_move, best_utility


######################################################################
############ DON'T WRITE ANY CODE OUTSIDE THE CLASS! #################
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############
######################################################################
if __name__ == '__main__':
    import player_submission_tests as tests

    results = []
    for i in range(6):
        if i < 1:
            results.append(tests.beatMiniMax(CustomPlayer, True))
        else:
            results.append(tests.beatMiniMax(CustomPlayer, False))
    print(results)
